version: "3"
services:
  spotlight:
    image: dbpedia/spotlight-english
    entrypoint: spotlight.sh
    ports:
      - 9002:80
  opener:
    image: semlab/dadalytics-opener
    ports:
      - 9001:9001
  stanford:
    image: semlab/dadalytics-stanford-ner
    ports:
      - 9000:9000
  server:
    image: semlab/dadalytics-docker-ner-gateway
    ports:
      - 80:80
    links:
      - spotlight
      - opener
      - stanford
      