version: "3"
services:
  spotlight:
    image: dbpedia/spotlight-english
    entrypoint: spotlight.sh
    ports:
      - 9002:80
  opener:
    image: semlab/dadalytics-opener
    ports:
      - 9001:9001
  stanford:
    image: semlab/dadalytics-stanford-ner
    ports:
      - 9000:9000
  gateway:
    image: semlab/dadalytics-docker-ner-gateway
    ports:
      - 80:8080
      - 443:8443
      - 5001:8001
    volumes:
      - "/etc/certs:/etc/certs"
    environment:
      - SSL_PROD=true
      - SSL_ENABLED=true
      - SSL_DOMAINS=
      - SSL_EMAIL=
    links:
      - spotlight
      - opener
      - stanford
      